torch.gels has been deprecated since torch 1.3.0
when I called train_hybrid() function in iris_example.py, I got following error.
AttributeError: module 'torch' has no attribute 'gels'
After quick research I found torch.gels is deprecated after torch 1.3.0 for some reason (***sigh***).
I did quick check with iris example and it seems works fine. I'm not sure this fix is correct, so please check the code if you still working on this project! 
Thank you for your great implementation!